export const LOGIN_WITH_EMAIL_ACTION_TYPES = {
    LOGIN_WITH_EMAIL_REQUEST: "LOGIN_WITH_EMAIL_REQUEST",
    LOGIN_WITH_EMAIL_FULFILLED: "LOGIN_WITH_EMAIL_FULFILLED",
    LOGIN_WITH_EMAIL_REJECTED: "LOGIN_WITH_EMAIL_REJECTED"
};

export const CREATE_ACCOUNT_ACTION_TYPES = {
    CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
    CREATE_ACCOUNT_FULFILLED: "CREATE_ACCOUNT_FULFILLED",
    CREATE_ACCOUNT_REJECTED: "CREATE_ACCOUNT_REJECTED"
};

export const CREATE_MARKET_ACTION_TYPES = {
    CREATE_MARKET_REQUEST: "CREATE_MARKET_REQUEST",
    CREATE_MARKET_FULFILLED: "CREATE_MARKET_FULFILLED",
    CREATE_MARKET_REJECTED: "CREATE_MARKET_REJECTED"
};

export const GET_MARKET_ACTION_TYPES = {
    GET_MARKET_REQUEST: "GET_MARKET_REQUEST",
    GET_MARKET_FULFILLED: "GET_MARKET_FULFILLED",
    GET_MARKET_REJECTED: "GET_MARKET_REJECTED"
};

export const ADD_IMAGES_ACTION_TYPES = {
    ADD_IMAGES_REQUEST: "ADD_IMAGES_REQUEST",
    ADD_IMAGES_FULFILLED: "ADD_IMAGES_FULFILLED",
    ADD_IMAGES_REJECTED: "ADD_IMAGES_REJECTED"
};
